### ISSUE TITLE
Allow reservations from users without accounts?

### ISSUE THREAD

**Issue by AbitFishy** [AbitFishy/GenSpark-Restaurant-Reservation-System#3]
Since most restaurants accept reservations via phone, do we "allow" that, and allow reservations from the website from non-accounts?

**Comment by tkim013** [comment]
that seems like the way to go as a guest.  no saving personal data.  my vote is yes

**Comment by joeytharpe1** [comment]
i made it so a user have to be signed in to view the page, ill add another view for those not signed up with account
