### ISSUE TITLE
is it possible to add pagination to GET mappings for reservation and users ? and maybe sorting ? 

### ISSUE THREAD

**Issue by joeytharpe1** [AbitFishy/GenSpark-Restaurant-Reservation-System#74]
need it for front end table, and would be nice for admin as well. ill get working on admin in the morning. should be pretty easy to render two tables.

**Comment by tkim013** [comment]
I'll look into it.

**Comment by tkim013** [comment]
![image](https://user-images.githubusercontent.com/102111948/170827020-ebf01b3a-80a5-4150-a614-cfcaab7a50a8.png)
